"""empty message

Revision ID: 237abcf34b3b
Revises: be66402f2c9a
Create Date: 2024-03-17 18:35:36.146966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237abcf34b3b'
down_revision = 'be66402f2c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('starships_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user-favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-favorites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"user-favorites_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('favorite_starship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorite_planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorite_character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorite_character_id'], ['favorite-characters.id'], name='user-favorites_favorite_character_id_fkey'),
    sa.ForeignKeyConstraint(['favorite_planet_id'], ['favorite-planets.id'], name='user-favorites_favorite_planet_id_fkey'),
    sa.ForeignKeyConstraint(['favorite_starship_id'], ['favorite-starships.id'], name='user-favorites_favorite_starship_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user-favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user-favorites_pkey')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
