"""empty message

Revision ID: 602dcdc4f2ae
Revises: d17f8f75c5dc
Create Date: 2024-03-15 19:57:21.169097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602dcdc4f2ae'
down_revision = 'd17f8f75c5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
