"""empty message

Revision ID: be66402f2c9a
Revises: faa1b90b3afd
Create Date: 2024-03-16 14:03:52.200029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be66402f2c9a'
down_revision = 'faa1b90b3afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_starship_id', sa.Integer(), nullable=True),
    sa.Column('favorite_planet_id', sa.Integer(), nullable=True),
    sa.Column('favorite_character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_character_id'], ['favorite-characters.id'], ),
    sa.ForeignKeyConstraint(['favorite_planet_id'], ['favorite-planets.id'], ),
    sa.ForeignKeyConstraint(['favorite_starship_id'], ['favorite-starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user-favorites')
    # ### end Alembic commands ###
